{
 "title": "cloudhost-resources-quota-allocated-organisation-timeseries-dashboard (total and used)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "organisation_name",
    "query": {
     "query": "label_values(organisation_name)"
    }
   },
   {
    "name": "organisation_id",
    "query": {
     "query": "label_values({organisation_name=\"$organisation_name\"},organisation_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "organisation_vm_total",
   "type": "timeseries",
   "description": "organisation_vm_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "organisation_vm_total{organisation_id=\"$organisation_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "organisation_vm_used",
   "type": "timeseries",
   "description": "organisation_vm_used",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "organisation_vm_used{organisation_id=\"$organisation_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "organisation_ram_total",
   "type": "timeseries",
   "description": "organisation_ram_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "organisation_ram_total{organisation_id=\"$organisation_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "organisation_ram_used",
   "type": "timeseries",
   "description": "organisation_ram_consumed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "organisation_ram_used{organisation_id=\"$organisation_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "organisation_vcpu_total",
   "type": "timeseries",
   "description": "organisation_vcpu_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "organisation_vcpu_total{organisation_id=\"$organisation_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "organisation_vcpu_used",
   "type": "timeseries",
   "description": "organisation_vcpu_used",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "organisation_vcpu_used{organisation_id=\"$organisation_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "organisation_volume_total",
   "type": "timeseries",
   "description": "organisation_volume_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "organisation_volume_total{organisation_id=\"$organisation_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "organisation_volume_used",
   "type": "timeseries",
   "description": "organisation_volume_used",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "organisation_volume_used{organisation_id=\"$organisation_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "organisation_storage_total",
   "type": "timeseries",
   "description": "organisation_storage_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "organisation_storage_total{organisation_id=\"$organisation_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "organisation_storage_used",
   "type": "timeseries",
   "description": "organisation_storage_used",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "organisation_storage_used{organisation_id=\"$organisation_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "organisation_firewall_rule_total",
   "type": "timeseries",
   "description": "organisation_firewall_rule_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "organisation_firewall_rule_total{organisation_id=\"$organisation_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "organisation_firewall_rule_used",
   "type": "timeseries",
   "description": "organisation_firewall_rule_used",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "organisation_firewall_rule_used{organisation_id=\"$organisation_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "organisation_network_total",
   "type": "timeseries",
   "description": "organisation_network_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "organisation_network_total{organisation_id=\"$organisation_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "organisation_network_used",
   "type": "timeseries",
   "description": "organisation_network_used",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "organisation_network_used{organisation_id=\"$organisation_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "organisation_vpn_total",
   "type": "timeseries",
   "description": "organisation_vpn_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "organisation_vpn_total{organisation_id=\"$organisation_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "organisation_vpn_used",
   "type": "timeseries",
   "description": "organisation_vpn_used",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "organisation_vpn_used{organisation_id=\"$organisation_id\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}