{
 "title": "cloudhost-resources-quota-allocated-project-timeseries-dashboard (total and consumed)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "organisation_name",
    "query": {
     "query": "label_values(organisation_name)"
    }
   },
   {
    "name": "organisation_id",
    "query": {
     "query": "label_values({organisation_name=\"$organisation_name\"},organisation_id)"
    }
   },
   {
    "name": "project_id",
    "query": {
     "query": "label_values({organisation_id=\"$organisation_id\"},project_id)"
    }
   },
   {
    "name": "project_name",
    "query": {
     "query": "label_values({project_id=\"$project_id\"},project_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "project_vm_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "project_vm_total{organisation_id=\"$organisation_id\",project_id=\"$project_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "project_vm_consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "project_vm_consumed{organisation_id=\"$organisation_id\",project_id=\"$project_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "project_ram_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "project_ram_total{organisation_id=\"$organisation_id\",project_id=\"$project_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "project_ram_consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "project_ram_consumed{organisation_id=\"$organisation_id\",project_id=\"$project_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "project_vcpu_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "project_vcpu_total{organisation_id=\"$organisation_id\",project_id=\"$project_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "project_vcpu_consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "project_vcpu_consumed{organisation_id=\"$organisation_id\",project_id=\"$project_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "project_volume_total",
   "type": "timeseries",
   "description": "project_volume_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "project_volume_total{organisation_id=\"$organisation_id\",project_id=\"$project_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "project_volume_consumed",
   "type": "timeseries",
   "description": "project_volume_consumed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "project_volume_consumed{organisation_id=\"$organisation_id\",project_id=\"$project_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "project_storage_total",
   "type": "timeseries",
   "description": "project_storage_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "project_storage_total{organisation_id=\"$organisation_id\",project_id=\"$project_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "project_storage_consumed",
   "type": "timeseries",
   "description": "project_storage_consumed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "project_storage_consumed{organisation_id=\"$organisation_id\",project_id=\"$project_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "project_firewall_rule_total",
   "type": "timeseries",
   "description": "project_firewall_rule_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "project_firewall_rule_total{organisation_id=\"$organisation_id\",project_id=\"$project_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "project_firewall_rule_consumed",
   "type": "timeseries",
   "description": "project_firewall_rule_consumed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "project_firewall_rule_consumed{organisation_id=\"$organisation_id\",project_id=\"$project_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "project_network_total",
   "type": "timeseries",
   "description": "project_network_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "project_network_total{organisation_id=\"$organisation_id\",project_id=\"$project_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "project_network_consumed",
   "type": "timeseries",
   "description": "project_network_consumed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "project_network_consumed{organisation_id=\"$organisation_id\",project_id=\"$project_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "project_vpn_total",
   "type": "timeseries",
   "description": "project_vpn_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "project_vpn_total{organisation_id=\"$organisation_id\",project_id=\"$project_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "project_vpn_consumed",
   "type": "timeseries",
   "description": "project_vpn_consumed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "project_vpn_consumed{organisation_id=\"$organisation_id\",project_id=\"$project_id\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}